spring:
  config:
    import: "optional:configserver:http://localhost:8088"
  application:
    name: api-gateway

  cloud:
    gateway:
      routes: 
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/departments/**
            
            